Develop
fangchi0209/Origin-Repository pull request #5
Opened 2021-05-07 09:01 UTC by fangchi0209

李芳岐
http://3.114.221.246:3000/
http://3.114.221.246:3000/attraction/55

2021-05-07 09:15 UTC, cwpeng commented
等你的修正嘍 ~

2021-05-07 09:15 UTC, cwpeng requested changes
等你的修正嘍 ~

2021-05-09 13:49 UTC, cwpeng commented
網站似乎壞掉了 ~ 恢復之後請發 Review Request 給我哦 ~

2021-05-09 14:09 UTC, fangchi0209 commented
老師～
感謝提醒！ 剛剛已再次開啟網路連線, 再請老師驗收, 謝謝老師！

2021-05-09 14:13 UTC, cwpeng commented
請發 Review Request 給我哦 ~

2021-05-09 14:18 UTC, cwpeng approved these changes
OK 哦，大致上沒問題，這樣就可以 :)

不過景點下方的介紹文字建議行高稍微拉高一些，會比較舒服的 ~

2021-05-09 14:34 UTC, fangchi0209 commented
好的, 謝謝老師的建議 :)

2021-05-09 14:34 UTC, merged